config/routes.rb
Rails.application.routes.draw do

  resources :airports, only: :show
  resources :carriers, only: :show
  get "*any", via: :all, to: "home#index"
end

app/models/airport.rb
class Airport < ActiveRecord::Base
  belongs_to :market
  validates :code, presence: true
  has_many :flights, as: :origin_airport
  has_many :flights, as: :destination_airport
  has_many :carriers, through: :flights
  acts_as_list
  attr_accessor :volume

  def self.active
    Airport.where(active: true)
  end

  def departures
    Flight.where(origin_airport_id: self.id)
  end

  def arrivals
    Flight.where(destination_airport_id: self.id)
  end

  def nearby_airports
    nearby_airports = self.market.airports
    if nearby_airports.count < 6
      nearby_airports = self.market.airports + Airport.find(Flight.where(origin_airport_id: self.id).where(distance_group: 1).distinct.collect { |flight| flight.destination_airport_id }).sort_by { |airport| airport.on_time_departure_percentage}.reverse.first(6 - nearby_airports.count)
    end
    nearby_airports.uniq.sort_by { |airport| airport.on_time_departure_percentage}.reverse
  end

  def active?
    departures.any? || arrivals.any?
  end

  def on_time_departure_percentage
    delayed_departure_count = Delay.where(flight_id: departures).count
    on_time_departure_percentage = (departures.count - delayed_departure_count) * 100 / departures.count
  end

  def on_time_arrival_percentage
    delayed_arrival_count = Delay.where(flight_id: arrivals).count
    on_time_arrival_percentage = (arrivals.count - delayed_arrival_count) * 100 / arrivals.count
  end

  def average_departure_delay
   departures.where.not(departure_delay: 0).average('departure_delay').to_i
  end

  def average_arrival_delay
    arrivals.where.not(arrival_delay: 0).average('arrival_delay').to_i
  end

  def volume=(flights)
    case
      when flights > 2000
        'large'
      when (flights <= 2000 && flights > 1000)
        'medium'
      else
        'small'
    end
  end

end

app/models/carrier.rb
class Carrier < ActiveRecord::Base
  validates :code, presence: true
  has_many :flights
  has_many :airports, through: :flights, source: :origin_airport

  def self.active
    Carrier.where(active: true)
  end

  def delayed_flight_ids
    Delay.where(flight_id: self.flights).map {|delay| delay.flight_id}
  end

  def on_time_percentage
    total_flights = self.flights.count
    total_flights > 0 ? (total_flights - delayed_flight_ids.count) * 100 / total_flights : 0
  end

  def average_delay
    Delay.where(flight_id: self.flights).average('duration').to_i
  end

  def departs_from
    self.airports.uniq
  end
end

app/models/delay.rb
class Delay < ActiveRecord::Base
  belongs_to :flight
  belongs_to :delay_cause

end

app/models/delay_cause.rb
class DelayCause < ActiveRecord::Base
  has_many :delays
  has_many :flights, through: :delays

end

app/models/destination_airport.rb
class DestinationAirport < Airport
  has_many :flights
  has_many :carriers, through: :flights
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  has_many :delays
  has_many :delay_causes, through: :delays
  belongs_to :origin_airport
  belongs_to :destination_airport
  belongs_to :carrier

end

app/models/market.rb
class Market < ActiveRecord::Base
  has_many :airports

  validates :code, presence: true

end

app/models/origin_airport.rb
class OriginAirport < Airport
  has_many :flights
  has_many :carriers, through: :flights
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController

  def show
    @airport = Airport.find(params[:id])
    @carriers = OriginAirport.find(params[:id]).carriers.uniq
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carriers_controller.rb
class CarriersController < ApplicationController

  def show
    @carrier = Carrier.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @carriers = Carrier.active.order(:position)
    @airports = Airport.active
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/airports/show.html.erb
<% content_for :title, "#{@airport.name} On Time Performance" %>
<h1><%= @airport.name %> (<%= @airport.abbreviation %>)</h1>
<em><%= @airport.location %></em>
<ul>
  <li>On Time Departure Percentage: <%= @airport.on_time_departure_percentage %>%</li>
  <li>On Time Arrival Percentage: <%= @airport.on_time_arrival_percentage %>%</li>
  <li>Average Departure Delay: <%= @airport.average_departure_delay %> minutes</li>
  <li>Average Arrival Delay: <%= @airport.average_arrival_delay %> minutes</li>
</ul>

<h2>Nearby Airports - Ranked By Best On Time Percentage</h2>
 <ol>
  <% @airport.nearby_airports.each do |airport| %>
    <% if airport.id == @airport.id %>
      <li><%= airport.name %>, <em><%= airport.location %></em> -- On Time Percentage: <%= airport.on_time_departure_percentage %>% </li>
    <% else %>
      <li><%= link_to(airport.name, airport_path(airport)) %>, <em><%= airport.location %></em> -- On Time Percentage: <%= airport.on_time_departure_percentage %>% </li>
    <% end %>
  <% end %>
  </ol>

<h2>Carriers Flying Out of <%= @airport.abbreviation %></h2>
 <ul>
  <% @carriers.each do |carrier| %>
     <li><%= link_to(carrier.description, carrier_path(carrier)) %></li>
    <% end %>
  </ul>

app/views/carriers/show.html.erb
<% content_for :title, "#{@carrier.description} On Time Performance" %>
<h1><%= @carrier.description %></h1>

<ul>
  <li>On Time Percentage: <%= @carrier.on_time_percentage %>%</li>
  <li>Average Delay: <%= @carrier.average_delay %> minutes</li>
</ul>

<h2><%= @carrier.description %> Flies Out Of</h2>
  <ul>
  <% @carrier.departs_from.each do |airport| %>
     <li><%= link_to(airport.name, airport_path(airport)) %></li>
    <% end %>
  </ul>

app/views/home/index.html.erb
<% content_for :title, "Best and Worst On Time Performance for Airports and Carriers" %>
<h1>Welcome to Flight Grader</h1>
<strong>Delays stink!</strong>
<p>Find out which airports and carriers have the best on time performance.</p>

<h2>Top 20 On Time Airports</h2>
<ol>
  <% @airports.order(:position).first(20).each do |airport| %>
    <li><%= link_to(airport.name, airport_path(airport)) %>, <em><%= airport.location %></em> -- On Time Percentage: <%= airport.on_time_departure_percentage %>% </li>
  <% end %>
</ol>

<h2>20 Worst On Time Airports</h2>
<ol>
  <% @airports.order(:position).last(20).reverse.each do |airport| %>
    <li><%= link_to(airport.name, airport_path(airport)) %>, <em><%= airport.location %></em> -- On Time Percentage: <%= airport.on_time_departure_percentage %>% </li>
  <% end %>
</ol>

<h2>Carriers Ranked by On Time Performance</h2>
<ol>
  <% @carriers.each do |carrier| %>
    <li><%= link_to(carrier.description, carrier_path(carrier)) %> -- On Time Percentage: <%= carrier.on_time_percentage %>% </li>
  <% end %>
</ol>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlightGrader -- <%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>